#! /usr/bin/env bash

# The version of the function file in format "x.y.z".
export JLB_FUNCEND_VERSION=1.0.0

# Public: Indicates where a function begins
#
# When debugging, states in terminal output where a function ends,
# as well as the provided return value. Also decrements JLB_DEBUG_DEPTH
# for use by jlb::debug
#
# $1 - OPTIONAL: the return value to be included in the output.
#
# Examples
#
#   jlb::funcEnd
#   jlb::funcEnd "${errcode}"
#
# Returns the result of jlb::debug
function jlb::funcEnd() {
	local errcode
	local retval="${*}"
	local str="END FUNCTION ${FUNCNAME[1]}"

	if [ ! -z "${retval}" ] ; then
		str="${str} with return value of $retval"
	fi

	((JLB_DEBUG_DEPTH--))
	export JLB_DEBUG_DEPTH

	jlb::debug "${str}" ; errcode=$?
	return ${errcode}
}

jlb::debug "Sourced file: ${BASH_SOURCE[0]}"
