#! /usr/bin/env bash

# The version of the function file in format "x.y.z".
export JLB_PRINTERR_VERSION=1.0.0

# Variable for changing prefix format
#JLB_ERROR_PREFIX="${JLB_PRINTF_RED}${JLB_PRINTF_CROSS} "
JLB_ERROR_PREFIX="ERR "

# Public: Prints to stderr
#
# Used to print error messages to stderr
#
# $1 - The string to print.
#
# Examples
#
#   jlb::printerr "Something went wrong!"
#
# Returns status of printf
function jlb::printerr() {
	local str="${*}"
	if [[ "$JLB_TEST" == "true" ]] ; then
		printf "${JLB_ERROR_PREFIX} %s\n" "${str}"
	else
		>&2 printf "${JLB_ERROR_PREFIX} %s\n" "${str}"
	fi

	return $?
}

jlb::debug "Sourced file: ${BASH_SOURCE[0]}"
