#! /usr/bin/env bash

#shellcheck disable=SC1090
source "$(git rev-parse --show-toplevel)/tests/common.sh"


testFiles+=( "functions/printerr" )
# 
test_printerr() {
	assertEquals "Verify printerr output" "${JLB_ERROR_PREFIX} test" "$(jlb::printerr "test")"
}


#shellcheck disable=SC2154
source "$shunit2Path"
